### ISSUE TITLE
Using two ou-bases?!

### ISSUE THREAD

**Issue by Paule2020** [matrix-org/matrix-synapse-ldap3#96] opened 2020-08-07 16:14 UTC
Hello,
I'm trying to use the LDAP-module for authenfitication. It works as long as I specify the base very detailed...
Works:
password_providers:
 - module: "ldap_auth_provider.LdapAuthProvider"
   config:
     enabled: true
     uri: "ldap://myServer:389"
     start_tls: false
     base: "ou=teachers, o=school"
     attributes:
        uid: "cn"
        mail: "mail"
        name: "givenName"
     #bind_dn:
     #bind_password:
     #filter: "(objectClass=posixAccount)"

However, teachers and pupils should be loged in by LDAP and so I tried:
password_providers:
 - module: "ldap_auth_provider.LdapAuthProvider"
   config:
     enabled: true
     uri: "ldap://myServer:389"
     start_tls: false
     base: "ou=teachers, o=school"
     base: "ou=pupil, o=school"
     attributes:
        uid: "cn"
        mail: "mail"
        name: "givenName"
     #bind_dn:
     #bind_password:
     #filter: "(objectClass=posixAccount)"
With the cfg above only pupils can log in, no teachers.

When no ou ist given (see below) , there is a error in the log file: 
ldap_auth_provider - 385 -INFO -Binding against LDAP faild for "cn=myName, o = school" failed: invalidCredentials
password_providers:
 - module: "ldap_auth_provider.LdapAuthProvider"
   config:
     enabled: true
     uri: "ldap://myServer:389"
     start_tls: false
     base: "o=school"
     attributes:
        uid: "cn"
        mail: "mail"
        name: "givenName"
     #bind_dn:
     #bind_password:
     #filter: "(objectClass=posixAccount)"

Any ideas how I can use ou=teachers AND ou=pupils?

**Comment by clokep** [comment] 2020-08-07 16:51
I believe that this is a duplicate of #66.

**Closed by clokep** 2020-08-07 16:51 UTC
