### ISSUE TITLE
Password change leads to multiple valid passwords.

### ISSUE THREAD

**Issue by MB175** [matrix-org/matrix-synapse-ldap3#153] opened 2022-01-06 23:35 UTC
First of all I'm not completely sure if this is caused by the ldap3 module or some ldap behavior.

**Describe the bug**
If a user changes his password, for example with the help of elements, the ldap password is not changed and two valid passwords exist.

**To Reproduce**
1. Change password with Elements
2. Login with new password -> works
3. Login with persistent LDAP password -> works

**Expected behavior**
Password should also be changed in LDAP.

**Additional context**
Users could think they successfully changed their compromised password, but in fact they did not.

#50 might be related.

**Comment by clokep** [comment] 2022-01-07 13:34
This is either a duplicate of #50 or a misconfiguration. You might want to checkout [the `password_config.localdb_enabled` setting](https://github.com/matrix-org/synapse/blob/9ec46d6231c267a1aa25c96b5d86822c7da8fca9/docs/sample_config.yaml#L2110-L2114) for Synapse. If this is disabled than the local database is never used for passwords and users should not be able to change their password.

**Closed by clokep** 2022-01-07 13:34 UTC

**Comment by MB175** [comment] 2022-01-07 23:09
I imagine this could be a good work around thanks for the info.

**Comment by clokep** [comment] 2022-01-08 00:34
Do shout if you think you're still seeing a bug after taking a look at that setting!
