### ISSUE TITLE
Fix UTF-8 encoding in Python LDAP connection on Matrix LDAP3 provider

### ISSUE THREAD

**Issue by MurzNN** [matrix-org/matrix-synapse-ldap3#33] opened 2017-07-11 07:43 UTC
At now matrix-synapse-ldap3 have problem with UTF-8 encoding on LDAP connection, so there are auth problems if users contain names in non-ascii characters.
Here is patch to fix this problem: https://github.com/slipeer/synapse-ldap-password-provider/commit/0370fbcbadab88bdfc8fac5f250ba470c7bc1960
I test and it works well. Please backport it to Matrix LDAP module core.

**Comment by maxidor** [comment] 2017-07-11 07:59
Allowing UTF-8 that way without further checks breaks the Matrix spec since you would allow non-ascii characters if the username had such characters.

So while it solve a problem, it creates another...

**Comment by MurzNN** [comment] 2017-07-11 09:10
This patch only change the connection encoding, because without this Russian strings are represented as `ÐÐ»ÐµÐºÑÐµÐ¹ ÐÐ¾ÑÐµÐ¿Ð¾Ð²` instead of `Алексей Корепов`, here is lines from log:
with patch:
```
2017-07-11 09:44:02,477 - ldap_auth_provider - 298 - INFO - POST-37- Binding against LDAP failed for 'CN=Алексей Корепов,CN=Users,DC=office,DC=homeserver,DC=ru' failed: invalidCredentials
```
without patch:
```
2017-07-11 10:02:12,668 - ldap_auth_provider - 298 - INFO - POST-4- Binding against LDAP failed for 'CN=ÐÐ»ÐµÐºÑÐµÐ¹ ÐÐ¾ÑÐµÐ¿Ð¾Ð²,CN=Users,DC=office,DC=homeserver,DC=ru' failed: invalidCredentials
```
So with or without this patch - synapse will receive non-ascii characters from LDAP server.

At now my LDAP database contains usernames in Russian (not logins), so I can't configure synapse to work with my database without this patch. Same problems will have all other non-English companines.

**Comment by maxidor** [comment] 2017-07-11 09:17
I agree, the change is needed to handle such LDAP.
I was just pointing out that this change alone will just move the current problem somewhere else.

**Comment by richvdh** [comment] 2021-06-18 13:59
I think this is basically a duplicate of #72

**Closed by richvdh** 2021-06-18 13:59 UTC
