### ISSUE TITLE
Import user profile picture from thumbnailPhoto (Active Directory)

### ISSUE THREAD

**Issue by kevin-olbrich** [matrix-org/matrix-synapse-ldap3#110] opened 2020-11-23 10:45 UTC
**Is your feature request related to a problem? Please describe.**
Users can upload a profile picture using e.g. Element but AD might already provide one using "thumbnailPhoto" attribute.

**Describe the solution you'd like**
When in AD mode, synapse could fetch thumbnailPhoto (type: binary, image-type: jpeg).

**Describe alternatives you've considered**
Theres also jpegPhoto (multi-val, multi-fileformat) which is more standards compliant but is not unsed by most applications. Most use thumbnailPhoto, at least in AD context.

**Additional context**
http://woshub.com/how-to-import-user-photo-to-active-directory-using-powershell/

**Comment by clokep** [comment] 2020-11-23 13:33
I think this is a generally a duplicate of #108. I'm going to close this.

**Closed by clokep** 2020-11-23 13:33 UTC
