### ISSUE TITLE
An exception handling is required when loading user data from the LDAP attribute

### ISSUE THREAD

**Issue by slipeer** [matrix-org/matrix-synapse-ldap3#25] opened 2017-03-09 13:42 UTC
An exception handling is required when loading user data from the LDAP attribute.
When the attribute specified in the configuration is not filled in, the user does not pass the authorization and no error in logs that indicates the cause of the failure.

**Comment by mweinelt** [comment] 2017-03-09 13:43
duplicate of #14

**Closed by mweinelt** 2017-03-09 13:43 UTC
